--------------------------------------------------------------------------------------------------
--		----	  |			  |			|		 |				|    --    |      ----			--
--		----	  |			  |			|		 |				|    --	   |      ----			--
--		----	  |		-------	   -----|	 ---------		-----          -      ----	   -------
--		----	  |			---			|		 -----		------        --      ----			--
--		----	  |			---			|		 -----		-------	 	 ---      ----			--
--		----	  |		-------	   ----------	 -----		-------		 ---      ----	   -------
--			|	  |		-------			|		 -----		-------		 ---		  |			--
--			|	  |		-------			|	 	 -----		-------		 ---		  |			--
--------------------------------------------------------------------------------------------------

-- Litter Types

return {
	{category="grime",name="overlay_grime_floor_01_23"},
	{category="grime",name="overlay_grime_floor_01_22"},
	{category="grime",name="overlay_grime_floor_01_21"},
	{category="grime",name="overlay_grime_floor_01_20"},
	{category="grime",name="overlay_grime_floor_01_15"},
	{category="grime",name="overlay_grime_floor_01_14"},
	{category="grime",name="overlay_grime_floor_01_13"},
	{category="grime",name="overlay_grime_floor_01_12"},
	{category="blood",name="overlay_blood_floor_01_46"},
	{category="blood",name="overlay_blood_floor_01_45"},
	{category="blood",name="overlay_blood_floor_01_44"},
	{category="blood",name="overlay_blood_floor_01_43"},
	{category="blood",name="overlay_blood_floor_01_42"},
	{category="blood",name="overlay_blood_floor_01_41"},
	{category="blood",name="overlay_blood_floor_01_40"},
	{category="blood",name="overlay_blood_floor_01_39"},
	{category="blood",name="overlay_blood_floor_01_38"},
	{category="blood",name="overlay_blood_floor_01_37"},
	{category="blood",name="overlay_blood_floor_01_36"},
	{category="blood",name="overlay_blood_floor_01_35"},
	{category="blood",name="overlay_blood_floor_01_34"},
	{category="blood",name="overlay_blood_floor_01_33"},
	{category="blood",name="overlay_blood_floor_01_32"},
	{category="blood",name="overlay_blood_floor_01_23"},
	{category="blood",name="overlay_blood_floor_01_22"},
	{category="blood",name="overlay_blood_floor_01_21"},
	{category="blood",name="overlay_blood_floor_01_20"},
	{category="blood",name="overlay_blood_floor_01_19"},
	{category="blood",name="overlay_blood_floor_01_18"},
	{category="blood",name="overlay_blood_floor_01_15"},
	{category="blood",name="overlay_blood_floor_01_14"},
	{category="blood",name="overlay_blood_floor_01_13"},
	{category="blood",name="overlay_blood_floor_01_12"},
	{category="blood",name="overlay_blood_floor_01_11"},
	{category="blood",name="overlay_blood_floor_01_10"},
	{category="blood",name="overlay_blood_floor_01_7"},
	{category="blood",name="overlay_blood_floor_01_6"},
	{category="blood",name="overlay_blood_floor_01_5"},
	{category="blood",name="overlay_blood_floor_01_4"},
	{category="blood",name="overlay_blood_floor_01_3"},
	{category="blood",name="overlay_blood_floor_01_2"},
	{category="blood",name="overlay_blood_floor_01_1"},
	{category="blood",name="overlay_blood_floor_01_0"},
	{category="wood",name="LS_Scraps_Wood_0"},
	{category="wood",name="LS_Scraps_Wood_1"},
	{category="wood",name="LS_Scraps_Wood_2"},
	{category="wood",name="LS_Scraps_Wood_3"},
	{category="wood",name="LS_Scraps_Wood_4"},
	{category="wood",name="LS_Scraps_Wood_5"},
	{category="wood",name="LS_Scraps_Wood_6"},
	{category="wood",name="LS_Scraps_Wood_7"},	
	{category="wood",name="LS_Scraps_Wood_8"},
	{category="cloth",name="LS_Scraps_Cloth_0"},
	{category="cloth",name="LS_Scraps_Cloth_1"},
	{category="cloth",name="LS_Scraps_Cloth_2"},
	{category="cloth",name="LS_Scraps_Cloth_3"},
	{category="cloth",name="LS_Scraps_Cloth_4"},
	{category="cloth",name="LS_Scraps_Cloth_5"},
	{category="cloth",name="LS_Scraps_Cloth_6"},
	{category="cloth",name="LS_Scraps_Cloth_7"},
	{category="metal",name="LS_Scraps_Metal_0"},
	{category="metal",name="LS_Scraps_Metal_1"},
	{category="metal",name="LS_Scraps_Metal_2"},
	{category="metal",name="LS_Scraps_Metal_3"},
	{category="metal",name="LS_Scraps_Metal_4"},
	{category="metal",name="LS_Scraps_Metal_5"},
	{category="metal",name="LS_Scraps_Metal_6"},
	{category="metal",name="LS_Scraps_Metal_7"},
	{category="metal",name="LS_Scraps_Metal_8"},
	{category="metal",name="LS_Scraps_Metal_9"},
	{category="metal",name="LS_Scraps_Metal_10"},
	{category="metal",name="LS_Scraps_Metal_11"},
	{category="metal",name="LS_Scraps_Metal_12"},
	{category="metal",name="LS_Scraps_Metal_13"},
	{category="metal",name="LS_Scraps_Metal_14"},
	{category="metal",name="LS_Scraps_Metal_15"},
	{category="metal",name="LS_Scraps_Metal_16"},
	{category="metal",name="LS_Scraps_Metal_17"},
	{category="metal",name="LS_Scraps_Metal_18"},
	{category="metal",name="LS_Scraps_Metal_19"},
	{category="metal",name="LS_Scraps_Metal_20"},
	{category="metal",name="LS_Scraps_Metal_21"},
	{category="metal",name="LS_Scraps_Metal_22"},
	{category="metal",name="LS_Scraps_Metal_23"},
	{category="metal",name="LS_Scraps_Metal_24"},
	{category="metal",name="LS_Scraps_Metal_25"},
	{category="metal",name="LS_Scraps_Metal_26"},
	{category="metal",name="LS_Scraps_Metal_27"},
	{category="metal",name="LS_Scraps_Metal_28"},
	{category="metal",name="LS_Scraps_Metal_29"},
	{category="food",name="LS_Scraps_Food_0"},
	{category="food",name="LS_Scraps_Food_1"},
	{category="food",name="LS_Scraps_Food_2"},
	{category="food",name="LS_Scraps_Food_3"},
	{category="food",name="LS_Scraps_Food_4"},
	{category="food",name="LS_Scraps_Food_5"},
	{category="food",name="LS_Scraps_Food_6"},
	{category="food",name="LS_Scraps_Food_7"},
	{category="food",name="LS_Scraps_Food_8"},
	{category="food",name="LS_Scraps_Food_9"},
	{category="food",name="LS_Scraps_Food_10"},
	{category="food",name="LS_Scraps_Food_11"},
	{category="food",name="LS_Scraps_Food_12"},
	{category="food",name="LS_Scraps_Food_13"},
	{category="food",name="LS_Scraps_Food_14"},
	{category="food",name="LS_Scraps_Food_15"},
	{category="food",name="LS_Scraps_Food_16"},
	{category="food",name="LS_Scraps_Food_17"},
	{category="food",name="LS_Scraps_Food_18"},
	{category="food",name="LS_Scraps_Food_19"},
	{category="food",name="LS_Scraps_Food_20"},
	{category="food",name="LS_Scraps_Food_21"},
	{category="food",name="LS_Scraps_Food_22"},

}
