--------------------------------------------------------------------------------------------------
--		----	  |			  |			|		 |				|    --    |      ----			--
--		----	  |			  |			|		 |				|    --	   |      ----			--
--		----	  |		-------	   -----|	 ---------		-----          -      ----	   -------
--		----	  |			---			|		 -----		------        --      ----			--
--		----	  |			---			|		 -----		-------	 	 ---      ----			--
--		----	  |		-------	   ----------	 -----		-------		 ---      ----	   -------
--			|	  |		-------			|		 -----		-------		 ---		  |			--
--			|	  |		-------			|	 	 -----		-------		 ---		  |			--
--------------------------------------------------------------------------------------------------

-- ANIMATIONS FOR INSTRUMENTS

return {

	{instrument="vocal",level=4,name="Bob_DancingClubVibing",keyframes=682,isSit=1},
	{instrument="vocal",level=6,name="Bob_DancingClubVibing",keyframes=682,isSit=1},
	{instrument="vocal",level=8,name="Bob_DancingClubVibing",keyframes=682,isSit=1},

	{instrument="Piano",level=0,name="Bob_PlayPianoExperiencedA",keyframes=682},
	{instrument="Piano",level=0,name="Bob_PlayPianoExperiencedA",keyframes=682},
	{instrument="Piano",level=0,name="Bob_PlayPianoExperiencedA",keyframes=682},
	{instrument="Piano",level=1,name="Bob_PlayPianoExperiencedA",keyframes=682},
	{instrument="Piano",level=1,name="Bob_PlayPianoExperiencedA",keyframes=682},
	{instrument="Piano",level=1,name="Bob_PlayPianoExperiencedA",keyframes=682},
	{instrument="Piano",level=2,name="Bob_PlayPianoExperiencedA",keyframes=682},
	{instrument="Piano",level=2,name="Bob_PlayPianoExperiencedA",keyframes=682},
	{instrument="Piano",level=2,name="Bob_PlayPianoExperiencedA",keyframes=682},
	{instrument="Piano",level=3,name="Bob_PlayPianoExperiencedA",keyframes=682},
	{instrument="Piano",level=4,name="Bob_PlayPianoExperiencedA",keyframes=682},
	{instrument="Piano",level=4,name="Bob_PlayPianoExperiencedA",keyframes=682},
	{instrument="Piano",level=5,name="Bob_PlayPianoExperiencedA",keyframes=682},
	{instrument="Piano",level=6,name="Bob_PlayPianoExperiencedA",keyframes=682},
	{instrument="Piano",level=7,name="Bob_PlayPianoExperiencedA",keyframes=682},
	{instrument="Piano",level=8,name="Bob_PlayPianoExperiencedA",keyframes=682},
	{instrument="Piano",level=9,name="Bob_PlayPianoExperiencedA",keyframes=682},
	{instrument="Piano",level=10,name="Bob_PlayPianoExperiencedA",keyframes=682},

	{instrument="Flute",level=0,name="Bob_PlayFluteDefaultBeginner",keyframes=682,isSit=1},
	{instrument="Flute",level=0,name="Bob_PlayFluteBeginnerA",keyframes=682,isSit=0},
	{instrument="Flute",level=1,name="Bob_PlayFluteDefaultBeginner",keyframes=682,isSit=1},
	{instrument="Flute",level=1,name="Bob_PlayFluteExperiencedA",keyframes=682,isSit=0},
	{instrument="Flute",level=1,name="Bob_PlayFluteExperiencedB",keyframes=682,isSit=0},
	{instrument="Flute",level=1,name="Bob_PlayFluteExperiencedC",keyframes=682,isSit=0},
	{instrument="Flute",level=4,name="Bob_PlayFluteDefault",keyframes=682,isSit=1},
	{instrument="Flute",level=4,name="Bob_PlayFluteProficientA",keyframes=682,isSit=0},
	{instrument="Flute",level=6,name="Bob_PlayFluteProficientB",keyframes=682,isSit=0},
	{instrument="Flute",level=6,name="Bob_PlayFluteProficientC",keyframes=682,isSit=0},
	{instrument="Flute",level=8,name="Bob_PlayFluteDefault",keyframes=682,isSit=1},
	{instrument="Flute",level=8,name="Bob_PlayFluteProficientA",keyframes=682,isSit=0},
	{instrument="Flute",level=8,name="Bob_PlayFluteProficientB",keyframes=682,isSit=0},
	{instrument="Flute",level=8,name="Bob_PlayFluteProficientC",keyframes=682,isSit=0},

	{instrument="GuitarAcoustic",level=0,name="Bob_PlayGuitarDefaultBeginner",keyframes=682,isSit=1},
	{instrument="GuitarAcoustic",level=0,name="Bob_PlayGuitarBeginnerA",keyframes=682,isSit=0},
	{instrument="GuitarAcoustic",level=1,name="Bob_PlayGuitarDefaultBeginner",keyframes=682,isSit=1},
	{instrument="GuitarAcoustic",level=1,name="Bob_PlayGuitarExperiencedA",keyframes=682,isSit=0},
	{instrument="GuitarAcoustic",level=1,name="Bob_PlayGuitarExperiencedB",keyframes=682,isSit=0},
	{instrument="GuitarAcoustic",level=1,name="Bob_PlayGuitarExperiencedC",keyframes=682,isSit=0},
	{instrument="GuitarAcoustic",level=4,name="Bob_PlayGuitarDefault",keyframes=682,isSit=1},
	{instrument="GuitarAcoustic",level=4,name="Bob_PlayGuitarProficientA",keyframes=682,isSit=0},
	{instrument="GuitarAcoustic",level=6,name="Bob_PlayGuitarProficientB",keyframes=682,isSit=0},
	{instrument="GuitarAcoustic",level=6,name="Bob_PlayGuitarProficientC",keyframes=682,isSit=0},
	{instrument="GuitarAcoustic",level=8,name="Bob_PlayGuitarDefault",keyframes=682,isSit=1},
	{instrument="GuitarAcoustic",level=8,name="Bob_PlayGuitarProficientA",keyframes=682,isSit=0},
	{instrument="GuitarAcoustic",level=8,name="Bob_PlayGuitarProficientB",keyframes=682,isSit=0},
	{instrument="GuitarAcoustic",level=8,name="Bob_PlayGuitarProficientC",keyframes=682,isSit=0},

	{instrument="GuitarElectric",level=0,name="Bob_PlayGuitarBassDefaultBeginner",keyframes=682,isSit=1},
	{instrument="GuitarElectric",level=0,name="Bob_PlayGuitarBassBeginnerA",keyframes=682,isSit=0},
	{instrument="GuitarElectric",level=1,name="Bob_PlayGuitarBassDefaultBeginner",keyframes=682,isSit=1},
	{instrument="GuitarElectric",level=1,name="Bob_PlayGuitarBassExperiencedA",keyframes=682,isSit=0},
	{instrument="GuitarElectric",level=1,name="Bob_PlayGuitarBassExperiencedB",keyframes=682,isSit=0},
	{instrument="GuitarElectric",level=1,name="Bob_PlayGuitarBassExperiencedC",keyframes=682,isSit=0},
	{instrument="GuitarElectric",level=4,name="Bob_PlayGuitarBassDefault",keyframes=682,isSit=1},
	{instrument="GuitarElectric",level=4,name="Bob_PlayGuitarBassProficientA",keyframes=682,isSit=0},
	{instrument="GuitarElectric",level=6,name="Bob_PlayGuitarBassProficientB",keyframes=682,isSit=0},
	{instrument="GuitarElectric",level=6,name="Bob_PlayGuitarBassProficientC",keyframes=682,isSit=0},
	{instrument="GuitarElectric",level=8,name="Bob_PlayGuitarBassDefault",keyframes=682,isSit=1},
	{instrument="GuitarElectric",level=8,name="Bob_PlayGuitarBassProficientA",keyframes=682,isSit=0},
	{instrument="GuitarElectric",level=8,name="Bob_PlayGuitarBassProficientB",keyframes=682,isSit=0},
	{instrument="GuitarElectric",level=8,name="Bob_PlayGuitarBassProficientC",keyframes=682,isSit=0},

	{instrument="GuitarElectricBass",level=0,name="Bob_PlayGuitarBassDefaultBeginner",keyframes=682,isSit=1},
	{instrument="GuitarElectricBass",level=0,name="Bob_PlayGuitarBassBeginnerA",keyframes=682,isSit=0},
	{instrument="GuitarElectricBass",level=1,name="Bob_PlayGuitarBassDefaultBeginner",keyframes=682,isSit=1},
	{instrument="GuitarElectricBass",level=1,name="Bob_PlayGuitarBassExperiencedA",keyframes=682,isSit=0},
	{instrument="GuitarElectricBass",level=1,name="Bob_PlayGuitarBassExperiencedB",keyframes=682,isSit=0},
	{instrument="GuitarElectricBass",level=1,name="Bob_PlayGuitarBassExperiencedC",keyframes=682,isSit=0},
	{instrument="GuitarElectricBass",level=4,name="Bob_PlayGuitarBassDefault",keyframes=682,isSit=1},
	{instrument="GuitarElectricBass",level=4,name="Bob_PlayGuitarBassProficientA",keyframes=682,isSit=0},
	{instrument="GuitarElectricBass",level=6,name="Bob_PlayGuitarBassProficientB",keyframes=682,isSit=0},
	{instrument="GuitarElectricBass",level=6,name="Bob_PlayGuitarBassProficientC",keyframes=682,isSit=0},
	{instrument="GuitarElectricBass",level=8,name="Bob_PlayGuitarBassDefault",keyframes=682,isSit=1},
	{instrument="GuitarElectricBass",level=8,name="Bob_PlayGuitarBassProficientA",keyframes=682,isSit=0},
	{instrument="GuitarElectricBass",level=8,name="Bob_PlayGuitarBassProficientB",keyframes=682,isSit=0},
	{instrument="GuitarElectricBass",level=8,name="Bob_PlayGuitarBassProficientC",keyframes=682,isSit=0},

	{instrument="Keytar",level=0,name="Bob_PlayKeytarDefaultBeginner",keyframes=682,isSit=1},
	{instrument="Keytar",level=0,name="Bob_PlayKeytarBeginnerA",keyframes=682,isSit=0},
	{instrument="Keytar",level=1,name="Bob_PlayKeytarDefaultBeginner",keyframes=682,isSit=1},
	{instrument="Keytar",level=1,name="Bob_PlayKeytarExperiencedA",keyframes=682,isSit=0},
	{instrument="Keytar",level=1,name="Bob_PlayKeytarExperiencedB",keyframes=682,isSit=0},
	{instrument="Keytar",level=1,name="Bob_PlayKeytarExperiencedC",keyframes=682,isSit=0},
	{instrument="Keytar",level=4,name="Bob_PlayKeytarDefault",keyframes=682,isSit=1},
	{instrument="Keytar",level=4,name="Bob_PlayKeytarProficientA",keyframes=682,isSit=0},
	{instrument="Keytar",level=6,name="Bob_PlayKeytarProficientB",keyframes=682,isSit=0},
	{instrument="Keytar",level=6,name="Bob_PlayKeytarProficientC",keyframes=682,isSit=0},
	{instrument="Keytar",level=8,name="Bob_PlayKeytarDefault",keyframes=682,isSit=1},
	{instrument="Keytar",level=8,name="Bob_PlayKeytarProficientA",keyframes=682,isSit=0},
	{instrument="Keytar",level=8,name="Bob_PlayKeytarProficientB",keyframes=682,isSit=0},
	{instrument="Keytar",level=8,name="Bob_PlayKeytarProficientC",keyframes=682,isSit=0},

	{instrument="Saxophone",level=0,name="Bob_PlaySaxophoneDefaultBeginner",keyframes=682,isSit=1},
	{instrument="Saxophone",level=0,name="Bob_PlaySaxophoneBeginnerA",keyframes=682,isSit=0},
	{instrument="Saxophone",level=1,name="Bob_PlaySaxophoneDefaultBeginner",keyframes=682,isSit=1},
	{instrument="Saxophone",level=1,name="Bob_PlaySaxophoneExperiencedA",keyframes=682,isSit=0},
	{instrument="Saxophone",level=1,name="Bob_PlaySaxophoneExperiencedB",keyframes=682,isSit=0},
	{instrument="Saxophone",level=1,name="Bob_PlaySaxophoneExperiencedC",keyframes=682,isSit=0},
	{instrument="Saxophone",level=4,name="Bob_PlaySaxophoneDefault",keyframes=682,isSit=1},
	{instrument="Saxophone",level=4,name="Bob_PlaySaxophoneProficientA",keyframes=682,isSit=0},
	{instrument="Saxophone",level=6,name="Bob_PlaySaxophoneProficientB",keyframes=682,isSit=0},
	{instrument="Saxophone",level=6,name="Bob_PlaySaxophoneProficientC",keyframes=682,isSit=0},
	{instrument="Saxophone",level=8,name="Bob_PlaySaxophoneDefault",keyframes=682,isSit=1},
	{instrument="Saxophone",level=8,name="Bob_PlaySaxophoneProficientA",keyframes=682,isSit=0},
	{instrument="Saxophone",level=8,name="Bob_PlaySaxophoneProficientB",keyframes=682,isSit=0},
	{instrument="Saxophone",level=8,name="Bob_PlaySaxophoneProficientC",keyframes=682,isSit=0},

	{instrument="Banjo",level=0,name="Bob_PlayGuitarDefaultBeginner",keyframes=682,isSit=1},
	{instrument="Banjo",level=0,name="Bob_PlayGuitarBeginnerA",keyframes=682,isSit=0},
	{instrument="Banjo",level=1,name="Bob_PlayGuitarDefaultBeginner",keyframes=682,isSit=1},
	{instrument="Banjo",level=1,name="Bob_PlayGuitarExperiencedA",keyframes=682,isSit=0},
	{instrument="Banjo",level=1,name="Bob_PlayGuitarExperiencedB",keyframes=682,isSit=0},
	{instrument="Banjo",level=1,name="Bob_PlayGuitarExperiencedC",keyframes=682,isSit=0},
	{instrument="Banjo",level=4,name="Bob_PlayGuitarDefault",keyframes=682,isSit=1},
	{instrument="Banjo",level=4,name="Bob_PlayGuitarProficientA",keyframes=682,isSit=0},
	{instrument="Banjo",level=6,name="Bob_PlayGuitarProficientB",keyframes=682,isSit=0},
	{instrument="Banjo",level=6,name="Bob_PlayGuitarProficientC",keyframes=682,isSit=0},
	{instrument="Banjo",level=8,name="Bob_PlayGuitarDefault",keyframes=682,isSit=1},
	{instrument="Banjo",level=8,name="Bob_PlayGuitarProficientA",keyframes=682,isSit=0},
	{instrument="Banjo",level=8,name="Bob_PlayGuitarProficientB",keyframes=682,isSit=0},
	{instrument="Banjo",level=8,name="Bob_PlayGuitarProficientC",keyframes=682,isSit=0},

	{instrument="Trumpet",level=0,name="Bob_PlayTrumpetDefaultBeginner",keyframes=682,isSit=1},
	{instrument="Trumpet",level=0,name="Bob_PlayTrumpetBeginnerA",keyframes=682,isSit=0},
	{instrument="Trumpet",level=1,name="Bob_PlayTrumpetDefaultBeginner",keyframes=682,isSit=1},
	{instrument="Trumpet",level=1,name="Bob_PlayTrumpetExperiencedA",keyframes=682,isSit=0},
	{instrument="Trumpet",level=1,name="Bob_PlayTrumpetExperiencedB",keyframes=682,isSit=0},
	{instrument="Trumpet",level=1,name="Bob_PlayTrumpetExperiencedC",keyframes=682,isSit=0},
	{instrument="Trumpet",level=4,name="Bob_PlayTrumpetDefault",keyframes=682,isSit=1},
	{instrument="Trumpet",level=4,name="Bob_PlayTrumpetProficientA",keyframes=682,isSit=0},
	{instrument="Trumpet",level=6,name="Bob_PlayTrumpetProficientB",keyframes=682,isSit=0},
	{instrument="Trumpet",level=6,name="Bob_PlayTrumpetProficientC",keyframes=682,isSit=0},
	{instrument="Trumpet",level=8,name="Bob_PlayTrumpetDefault",keyframes=682,isSit=1},
	{instrument="Trumpet",level=8,name="Bob_PlayTrumpetProficientA",keyframes=682,isSit=0},
	{instrument="Trumpet",level=8,name="Bob_PlayTrumpetProficientB",keyframes=682,isSit=0},
	{instrument="Trumpet",level=8,name="Bob_PlayTrumpetProficientC",keyframes=682,isSit=0},

	{instrument="Harmonica",level=0,name="Bob_PlayHarmonicaDefaultBeginner",keyframes=682,isSit=1},
	{instrument="Harmonica",level=0,name="Bob_PlayHarmonicaBeginnerA",keyframes=682,isSit=0},
	{instrument="Harmonica",level=1,name="Bob_PlayHarmonicaDefaultBeginner",keyframes=682,isSit=1},
	{instrument="Harmonica",level=1,name="Bob_PlayHarmonicaExperiencedA",keyframes=682,isSit=0},
	{instrument="Harmonica",level=1,name="Bob_PlayHarmonicaExperiencedB",keyframes=682,isSit=0},
	{instrument="Harmonica",level=1,name="Bob_PlayHarmonicaExperiencedC",keyframes=682,isSit=0},
	{instrument="Harmonica",level=4,name="Bob_PlayHarmonicaDefault",keyframes=682,isSit=1},
	{instrument="Harmonica",level=4,name="Bob_PlayHarmonicaProficientA",keyframes=682,isSit=0},
	{instrument="Harmonica",level=6,name="Bob_PlayHarmonicaProficientB",keyframes=682,isSit=0},
	{instrument="Harmonica",level=6,name="Bob_PlayHarmonicaProficientC",keyframes=682,isSit=0},
	{instrument="Harmonica",level=8,name="Bob_PlayHarmonicaDefault",keyframes=682,isSit=1},
	{instrument="Harmonica",level=8,name="Bob_PlayHarmonicaProficientA",keyframes=682,isSit=0},
	{instrument="Harmonica",level=8,name="Bob_PlayHarmonicaProficientB",keyframes=682,isSit=0},
	{instrument="Harmonica",level=8,name="Bob_PlayHarmonicaProficientC",keyframes=682,isSit=0},

	{instrument="Violin",level=0,name="Bob_PlayViolinDefaultBeginner",keyframes=682,isSit=1},
	{instrument="Violin",level=0,name="Bob_PlayViolinBeginnerA",keyframes=682,isSit=0},
	{instrument="Violin",level=1,name="Bob_PlayViolinDefaultBeginner",keyframes=682,isSit=1},
	{instrument="Violin",level=1,name="Bob_PlayViolinExperiencedA",keyframes=682,isSit=0},
	{instrument="Violin",level=1,name="Bob_PlayViolinExperiencedB",keyframes=682,isSit=0},
	{instrument="Violin",level=1,name="Bob_PlayViolinExperiencedC",keyframes=682,isSit=0},
	{instrument="Violin",level=4,name="Bob_PlayViolinDefault",keyframes=682,isSit=1},
	{instrument="Violin",level=4,name="Bob_PlayViolinProficientA",keyframes=682,isSit=0},
	{instrument="Violin",level=6,name="Bob_PlayViolinProficientB",keyframes=682,isSit=0},
	{instrument="Violin",level=6,name="Bob_PlayViolinProficientC",keyframes=682,isSit=0},
	{instrument="Violin",level=8,name="Bob_PlayViolinDefault",keyframes=682,isSit=1},
	{instrument="Violin",level=8,name="Bob_PlayViolinProficientA",keyframes=682,isSit=0},
	{instrument="Violin",level=8,name="Bob_PlayViolinProficientB",keyframes=682,isSit=0},
	{instrument="Violin",level=8,name="Bob_PlayViolinProficientC",keyframes=682,isSit=0},

}
