table.insert(ZombiesZoneDefinition.Army, {name = "Lynx_Black", chance = 3})
table.insert(ZombiesZoneDefinition.Army, {name = "Lynx_Green", chance = 3})
table.insert(ZombiesZoneDefinition.Army, {name = "Lynx_BallisticFaceShield_Black", chance = 3})
table.insert(ZombiesZoneDefinition.Army, {name = "Lynx_BallisticFaceShield_Green", chance = 3})
table.insert(ZombiesZoneDefinition.Army, {name = "Lynx_RysT_Black", chance = 3})
table.insert(ZombiesZoneDefinition.Army, {name = "Lynx_RysT_Black", chance = 3})
table.insert(ZombiesZoneDefinition.Army, {name = "Lynx_Clothes", chance = 15})

table.insert(ZombiesZoneDefinition.SecretBase, {name = "Lynx_Black", chance = 20})
table.insert(ZombiesZoneDefinition.SecretBase, {name = "Lynx_Green", chance = 20})
table.insert(ZombiesZoneDefinition.SecretBase, {name = "Lynx_BallisticFaceShield_Black", chance = 20})
table.insert(ZombiesZoneDefinition.SecretBase, {name = "Lynx_BallisticFaceShield_Green", chance = 20})
table.insert(ZombiesZoneDefinition.SecretBase, {name = "Lynx_RysT_Black", chance = 20})
table.insert(ZombiesZoneDefinition.SecretBase, {name = "Lynx_RysT_Black", chance = 20})
table.insert(ZombiesZoneDefinition.SecretBase, {name = "Lynx_Clothes", chance = 20})
