--------------------------------------------------------------------------------------------------
--		----	  |			  |			|		 |				|    --    |      ----			--
--		----	  |			  |			|		 |				|    --	   |      ----			--
--		----	  |		-------	   -----|	 ---------		-----          -      ----	   -------
--		----	  |			---			|		 -----		------        --      ----			--
--		----	  |			---			|		 -----		-------	 	 ---      ----			--
--		----	  |		-------	   ----------	 -----		-------		 ---      ----	   -------
--			|	  |		-------			|		 -----		-------		 ---		  |			--
--			|	  |		-------			|	 	 -----		-------		 ---		  |			--
--------------------------------------------------------------------------------------------------

-- KEYTAR DUET TRACKS
return {
	{level=4,sound="KeytarDuet04Summertime",length=173,name="ContextMenu_04_01_KD",actionType = "Bob_PlayKeytarExperiencedA",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=1,guitarelectric=0,guitarelectricbass=1,flute=1,saxophone=0,trumpet=1,violin=0,drums=0,piano=1,harmonica=0,vocalm=0,vocalf=1},
	{level=4,sound="KeytarDuet04LetsGroove",length=343,name="ContextMenu_04_02_KD",actionType="CanDoBackVocal",soundv="KeytarDuet04VocalLetsGroove",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=0,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=1,trumpet=1,violin=0,drums=0,piano=0,harmonica=0,vocalm=1,vocalf=0},
	{level=4,sound="KeytarDuet04YaketySax",length=122,name="ContextMenu_04_03_KD",actionType = "Bob_PlayKeytarExperiencedA",isaddon=0,
	banjo=1,keytar=0,guitaracoustic=0,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=1,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=0,vocalf=0},
	{level=4,sound="KeytarDuet04OhSusanna",length=74,name="ContextMenu_04_04_KD",actionType = "Bob_PlayKeytarExperiencedA",isaddon=0,
	banjo=1,keytar=0,guitaracoustic=0,guitarelectric=0,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=1,vocalf=0},
	{level=4,sound="KeytarDuet04LaBamba",length=139,name="ContextMenu_04_05_KD",actionType = "Bob_PlayKeytarExperiencedA",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=1,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=1,vocalf=0},
	{level=4,sound="KeytarDuet04OnceInRoyalDavidsCity",length=146,name="ContextMenu_04_06_KD",actionType = "Bob_PlayKeytarExperiencedA",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=0,guitarelectric=0,guitarelectricbass=1,flute=1,saxophone=0,trumpet=1,violin=0,drums=0,piano=0,harmonica=0,vocalm=1,vocalf=0},
	{level=5,sound="KeytarDuet05WhenTheSaintsGoMarchingIn",length=104,name="ContextMenu_05_01_KD",actionType = "Bob_PlayKeytarProficientC",isaddon=0,
	banjo=1,keytar=0,guitaracoustic=0,guitarelectric=0,guitarelectricbass=0,flute=1,saxophone=1,trumpet=1,violin=0,drums=0,piano=0,harmonica=0,vocalm=1,vocalf=0},       
	{level=5,sound="KeytarDuet05FeeFye",length=149,name="ContextMenu_05_02_KD",actionType = "Bob_PlayKeytarProficientC",isaddon=0,
	banjo=1,keytar=0,guitaracoustic=1,guitarelectric=0,guitarelectricbass=1,flute=1,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=1,vocalf=0},
	{level=5,sound="KeytarDuet05ThePinkPanther",length=156,name="ContextMenu_05_03_KD",actionType = "Bob_PlayKeytarProficientC",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=0,guitarelectric=1,guitarelectricbass=1,flute=1,saxophone=1,trumpet=1,violin=0,drums=0,piano=1,harmonica=0,vocalm=0,vocalf=0},  	
	{level=5,sound="KeytarDuet05BluesInE",length=193,name="ContextMenu_05_04_KD",actionType = "Bob_PlayKeytarProficientC",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=1,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=0},  
	{level=5,sound="KeytarDuet05IWannaDanceWithSomebody",length=296,name="ContextMenu_05_05_KD",actionType="CanDoBackVocal",soundv="KeytarDuetVocal05IWannaDanceWithSomebody",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=0,guitarelectric=1,guitarelectricbass=0,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=1},   
	{level=6,sound="KeytarDuet06Banjo",length=255,name="ContextMenu_06_01_KD",actionType="CanDoBackVocal",soundv="KeytarDuet06VocalBanjo",isaddon=0,
	banjo=1,keytar=0,guitaracoustic=1,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=1,vocalf=0},       
	{level=6,sound="KeytarDuet06CauseWeveEndedAsLovers",length=343,name="ContextMenu_06_02_KD",actionType = "Bob_PlayKeytarProficientA",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=0,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=0},
	{level=6,sound="KeytarDuet06MyWay",length=275,name="ContextMenu_06_03_KD",actionType = "Bob_PlayKeytarProficientA",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=1,guitarelectric=0,guitarelectricbass=1,flute=1,saxophone=1,trumpet=1,violin=0,drums=0,piano=0,harmonica=0,vocalm=1,vocalf=0},       
	{level=6,sound="KeytarDuet06SummerOf69",length=204,name="ContextMenu_06_04_KD",actionType="CanDoBackVocal",soundv="KeytarDuetVocal06SummerOf69",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=0,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=1,vocalf=0},   
	{level=7,sound="KeytarDuet07GhostRidersInTheSky",length=312,name="ContextMenu_07_01_KD",actionType = "Bob_PlayKeytarProficientA",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=1,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=1,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=0},       
	{level=7,sound="KeytarDuet07Wave",length=172,name="ContextMenu_07_02_KD",actionType = "Bob_PlayKeytarProficientA",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=1,guitarelectric=0,guitarelectricbass=1,flute=1,saxophone=0,trumpet=1,violin=0,drums=0,piano=1,harmonica=0,vocalm=0,vocalf=0},      
	{level=7,sound="KeytarDuet07Creep",length=239,name="ContextMenu_07_03_KD",actionType="Bob_PlayKeytarProficientA",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=0,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=1,vocalf=0},
	{level=7,sound="KeytarDuet07Zombie",length=306,name="ContextMenu_07_04_KD",actionType="CanDoBackVocal",soundv="KeytarDuetVocal07Zombie",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=0,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=1},
	{level=8,sound="KeytarDuet08Europa",length=298,name="ContextMenu_08_01_KD",actionType = "Bob_PlayKeytarProficientA",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=0,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=0},    
	{level=8,sound="KeytarDuet08RideLikeTheWind",length=271,name="ContextMenu_08_02_KD",actionType="CanDoBackVocal",soundv="KeytarDuetVocal08RideLikeTheWind",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=1,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=1,trumpet=1,violin=0,drums=0,piano=1,harmonica=0,vocalm=1,vocalf=0},
	{level=8,sound="KeytarDuet08FeelsSoGood",length=581,name="ContextMenu_08_03_KD",actionType = "Bob_PlayKeytarProficientA",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=1,guitarelectric=1,guitarelectricbass=1,flute=1,saxophone=1,trumpet=1,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=0},
	{level=9,sound="KeytarDuet09Radio80",length=189,name="ContextMenu_09_01_KD",actionType="CanDoBackVocal",soundv="KeytarDuetVocal09Radio80",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=0,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=1,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=1,vocalf=0},
	{level=6,sound="KeytarDuet06RiversofBabylon",length=245,name="ContextMenu_Duet_RiversofBabylon",actionType="Female",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=1,guitarelectric=0,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=1},
	{level=7,sound="KeytarDuet07TotalEclipseoftheHeart",length=276,name="ContextMenu_Duet_TotalEclipseoftheHeart",actionType="CanDoBackVocal",soundv="KeytarDuetVocal07TotalEclipseoftheHeart",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=0,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=0,vocalf=1},
	{level=7,sound="KeytarDuet07Kyrie",length=275,name="ContextMenu_Duet_Kyrie",actionType="CanDoBackVocal",soundv="KeytarDuetVocal07Kyrie",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=0,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=1,vocalf=0},
	{level=8,sound="KeytarDuet08Rasputin",length=267,name="ContextMenu_Duet_Rasputin",actionType="Female",isaddon=0,
	banjo=1,keytar=0,guitaracoustic=1,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=1,vocalf=1},
	{level=8,sound="KeytarDuet08WhataFeeling",length=234,name="ContextMenu_Duet_WhataFeeling",actionType="Female",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=0,guitarelectric=1,guitarelectricbass=0,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=1},
	{level=9,sound="KeytarDuet09SweetDreams",length=221,name="ContextMenu_Duet_SweetDreams",actionType="Female",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=0,guitarelectric=0,guitarelectricbass=0,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=0,vocalf=1},
	{level=10,sound="KeytarDuet10HoldingOutForAHero",length=351,name="ContextMenu_Duet_HoldingOutForAHero",actionType="CanDoBackVocal",soundv="KeytarDuetVocal10HoldingOutForAHero",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=0,guitarelectric=1,guitarelectricbass=0,flute=0,saxophone=0,trumpet=1,violin=0,drums=0,piano=1,harmonica=0,vocalm=0,vocalf=1},
	{level=5,sound="KeytarDuet05DannyBoy",length=256,name="ContextMenu_Duet_DannyBoy",actionType="Male",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=1,guitarelectric=0,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=1,vocalf=0},
	{level=5,sound="KeytarDuet05HouseoftheRisingSun",length=260,name="ContextMenu_Duet_HouseoftheRisingSun",actionType="Male",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=1,guitarelectric=0,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=1,vocalf=0},
	{level=5,sound="KeytarDuet05Maniac",length=265,name="ContextMenu_Duet_Maniac",actionType="CanDoBackVocal",soundv="KeytarDuetVocal05Maniac",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=0,guitarelectric=1,guitarelectricbass=0,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=1,vocalf=0},
	{level=5,sound="KeytarDuet05YouSpinMeRound",length=205,name="ContextMenu_Duet_YouSpinMeRound",actionType="Male",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=0,guitarelectric=0,guitarelectricbass=0,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=1,vocalf=0},
	{level=6,sound="KeytarDuet06Roxanne",length=199,name="ContextMenu_Duet_Roxanne",actionType="Male",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=0,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=1,vocalf=0},
	{level=7,sound="KeytarDuet07DownUnder",length=195,name="ContextMenu_Duet_DownUnder",actionType="Male",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=0,guitarelectric=1,guitarelectricbass=1,flute=1,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=1,vocalf=0},
	{level=7,sound="KeytarDuet07EveryBreathYouTake",length=252,name="ContextMenu_Duet_EveryBreathYouTake",actionType="Male",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=0,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=1,vocalf=0},
	{level=7,sound="KeytarDuet07LittleBrownJug",length=142,name="ContextMenu_Duet_LittleBrownJug",actionType="Male",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=1,guitarelectric=0,guitarelectricbass=1,flute=0,saxophone=1,trumpet=1,violin=0,drums=0,piano=1,harmonica=0,vocalm=1,vocalf=0},
	{level=9,sound="KeytarDuet09Africa",length=291,name="ContextMenu_Duet_Africa",actionType="Male",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=1,guitarelectric=1,guitarelectricbass=1,flute=1,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=1,vocalf=0},
	{level=9,sound="KeytarDuet09ImStillStanding",length=181,name="ContextMenu_Duet_ImStillStanding",actionType="Male",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=1,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=1,vocalf=0},
	{level=10,sound="KeytarDuet10DontYou",length=269,name="ContextMenu_Duet_DontYou",actionType="Male",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=0,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=1,vocalf=0},
	{level=10,sound="KeytarDuet10HoldtheLine",length=238,name="ContextMenu_Duet_HoldtheLine",actionType="Male",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=0,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=1,vocalf=0},
}
