--------------------------------------------------------------------------------------------------
--		----	  |			  |			|		 |				|    --    |      ----			--
--		----	  |			  |			|		 |				|    --	   |      ----			--
--		----	  |		-------	   -----|	 ---------		-----          -      ----	   -------
--		----	  |			---			|		 -----		------        --      ----			--
--		----	  |			---			|		 -----		-------	 	 ---      ----			--
--		----	  |		-------	   ----------	 -----		-------		 ---      ----	   -------
--			|	  |		-------			|		 -----		-------		 ---		  |			--
--			|	  |		-------			|	 	 -----		-------		 ---		  |			--
--------------------------------------------------------------------------------------------------

-- GUITAR ELECTRIC BASS DUET TRACKS
return {
	{level=4,sound="GuitarElectricBassDuet04Summertime",length=173,name="ContextMenu_04_01_GEBD",actionType = "Bob_PlayGuitarBassExperiencedB",isaddon=0,
	banjo=0,guitaracoustic=1,guitarelectric=0,guitarelectricbass=0,keytar=1,flute=1,saxophone=0,trumpet=1,violin=0,drums=0,piano=1,harmonica=0,vocalm=0,vocalf=1},
	{level=4,sound="GuitarElectricBassDuet04LetsGroove",length=343,name="ContextMenu_04_02_GEBD",actionType = "Bob_PlayGuitarBassExperiencedB",isaddon=0,
	banjo=0,guitaracoustic=0,guitarelectric=1,guitarelectricbass=0,keytar=1,flute=0,saxophone=1,trumpet=1,violin=0,drums=0,piano=0,harmonica=0,vocalm=1,vocalf=0},
	{level=4,sound="GuitarElectricBassDuet04YaketySax",length=122,name="ContextMenu_04_03_GEBD",actionType = "Bob_PlayGuitarBassExperiencedB",isaddon=0,
	banjo=1,guitaracoustic=0,guitarelectric=1,guitarelectricbass=0,keytar=1,flute=0,saxophone=1,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=0,vocalf=0},
	{level=4,sound="GuitarElectricBassDuet04OhSusanna",length=74,name="ContextMenu_04_04_GEBD",actionType = "Bob_PlayGuitarBassExperiencedB",isaddon=0,
	banjo=1,guitaracoustic=0,guitarelectric=0,guitarelectricbass=0,keytar=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=1,vocalf=0},
	{level=4,sound="GuitarElectricBassDuet04LaBamba",length=139,name="ContextMenu_04_05_GEBD",actionType = "Bob_PlayGuitarBassExperiencedB",isaddon=0,
	banjo=0,guitaracoustic=1,guitarelectric=1,guitarelectricbass=0,keytar=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=1,vocalf=0},
	{level=4,sound="GuitarElectricBassDuet04OnceInRoyalDavidsCity",length=146,name="ContextMenu_04_06_GEBD",actionType = "Bob_PlayGuitarBassExperiencedB",isaddon=0,
	banjo=0,guitaracoustic=0,guitarelectric=0,guitarelectricbass=0,keytar=1,flute=1,saxophone=0,trumpet=1,violin=0,drums=0,piano=0,harmonica=0,vocalm=1,vocalf=0},
	{level=5,sound="GuitarElectricBassDuet05FeeFye",length=149,name="ContextMenu_05_01_GEBD",actionType = "Bob_PlayGuitarBassProficientB",isaddon=0,
	banjo=1,guitaracoustic=1,guitarelectric=0,guitarelectricbass=0,keytar=1,flute=1,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=1,vocalf=0},       
	{level=5,sound="GuitarElectricBassDuet05ThePinkPanther",length=156,name="ContextMenu_05_02_GEBD",actionType = "Bob_PlayGuitarBassProficientB",isaddon=0,
	banjo=0,guitaracoustic=0,guitarelectric=1,guitarelectricbass=0,keytar=1,flute=1,saxophone=1,trumpet=1,violin=0,drums=0,piano=1,harmonica=0,vocalm=0,vocalf=0},           
	{level=5,sound="GuitarElectricBassDuet05BluesInE",length=193,name="ContextMenu_05_03_GEBD",actionType = "Bob_PlayGuitarBassProficientB",isaddon=0,
	banjo=0,guitaracoustic=1,guitarelectric=1,guitarelectricbass=0,keytar=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=0},   
	{level=6,sound="GuitarElectricBassDuet06Banjo",length=255,name="ContextMenu_06_01_GEBD",actionType = "Bob_PlayGuitarBassProficientB",isaddon=0,
	banjo=1,guitaracoustic=1,guitarelectric=1,guitarelectricbass=0,keytar=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=1,vocalf=0},       
	{level=6,sound="GuitarElectricBassDuet06CauseWeveEndedAsLovers",length=343,name="ContextMenu_06_02_GEBD",actionType = "Bob_PlayGuitarBassProficientB",isaddon=0,
	banjo=0,guitaracoustic=0,guitarelectric=1,guitarelectricbass=0,keytar=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=0},       
	{level=6,sound="GuitarElectricBassDuet06MyWay",length=275,name="ContextMenu_06_03_GEBD",actionType = "Bob_PlayGuitarBassProficientB",isaddon=0,
	banjo=0,guitaracoustic=1,guitarelectric=0,guitarelectricbass=0,keytar=1,flute=1,saxophone=1,trumpet=1,violin=0,drums=0,piano=0,harmonica=0,vocalm=1,vocalf=0},  
	{level=6,sound="GuitarElectricBassDuet06SummerOf69",length=204,name="ContextMenu_06_04_GEBD",actionType = "Bob_PlayGuitarBassProficientB",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=0,guitarelectric=1,guitarelectricbass=0,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=1,vocalf=0},   	
	{level=7,sound="GuitarElectricBassDuet07GhostRidersInTheSky",length=312,name="ContextMenu_07_01_GEBD",actionType = "Bob_PlayGuitarBassProficientB",isaddon=0,
	banjo=0,guitaracoustic=1,guitarelectric=1,guitarelectricbass=0,keytar=1,flute=0,saxophone=1,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=0},       
	{level=7,sound="GuitarElectricBassDuet07Wave",length=172,name="ContextMenu_07_02_GEBD",actionType = "Bob_PlayGuitarBassProficientB",isaddon=0,
	banjo=0,guitaracoustic=1,guitarelectric=0,guitarelectricbass=0,keytar=1,flute=1,saxophone=0,trumpet=1,violin=0,drums=0,piano=1,harmonica=0,vocalm=0,vocalf=0},
	{level=7,sound="GuitarElectricBassDuet07Creep",length=239,name="ContextMenu_07_03_GEBD",actionType="Bob_PlayGuitarBassProficientB",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=0,guitarelectric=1,guitarelectricbass=0,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=1,vocalf=0},
	{level=7,sound="GuitarElectricBassDuet07Zombie",length=306,name="ContextMenu_07_04_GEBD",actionType="Bob_PlayGuitarBassProficientB",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=0,guitarelectric=1,guitarelectricbass=0,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=1},
	{level=8,sound="GuitarElectricBassDuet08Europa",length=298,name="ContextMenu_08_01_GEBD",actionType = "Bob_PlayGuitarBassProficientB",isaddon=0,
	banjo=0,guitaracoustic=0,guitarelectric=1,guitarelectricbass=0,keytar=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=0},    
	{level=8,sound="GuitarElectricBassDuet08RideLikeTheWind",length=271,name="ContextMenu_08_02_GEBD",actionType = "Bob_PlayGuitarBassProficientB",isaddon=0,
	banjo=0,guitaracoustic=1,guitarelectric=1,guitarelectricbass=0,keytar=1,flute=0,saxophone=1,trumpet=1,violin=0,drums=0,piano=1,harmonica=0,vocalm=1,vocalf=0},    
	{level=8,sound="GuitarElectricBassDuet08FeelsSoGood",length=581,name="ContextMenu_08_03_GEBD",actionType = "Bob_PlayGuitarBassProficientB",isaddon=0,
	banjo=0,guitaracoustic=1,guitarelectric=1,guitarelectricbass=0,keytar=1,flute=1,saxophone=1,trumpet=1,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=0},
	{level=9,sound="GuitarElectricBassDuet09Radio80",length=189,name="ContextMenu_09_01_GEBD",actionType="Bob_PlayGuitarBassProficientB",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=0,guitarelectric=1,guitarelectricbass=0,flute=0,saxophone=1,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=1,vocalf=0},
	{level=4,sound="GuitarElectricBassDuet04Greensleeves",length=178,name="ContextMenu_Duet_Greensleeves",actionType="Female",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=1,guitarelectric=0,guitarelectricbass=0,flute=1,saxophone=1,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=0,vocalf=1},
	{level=6,sound="GuitarElectricBassDuet06RiversofBabylon",length=245,name="ContextMenu_Duet_RiversofBabylon",actionType="Female",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=1,guitarelectric=0,guitarelectricbass=0,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=1},
	{level=7,sound="GuitarElectricBassDuet07TotalEclipseoftheHeart",length=276,name="ContextMenu_Duet_TotalEclipseoftheHeart",actionType="Female",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=0,guitarelectric=1,guitarelectricbass=0,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=0,vocalf=1},
	{level=7,sound="GuitarElectricBassDuet07Kyrie",length=275,name="ContextMenu_Duet_Kyrie",actionType="CanDoBackVocal",soundv="GuitarElectricBassDuetVocal07Kyrie",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=0,guitarelectric=1,guitarelectricbass=0,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=1,vocalf=0},
	{level=8,sound="GuitarElectricBassDuet08Rasputin",length=267,name="ContextMenu_Duet_Rasputin",actionType="Female",isaddon=0,
	banjo=1,keytar=1,guitaracoustic=1,guitarelectric=1,guitarelectricbass=0,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=1,vocalf=1},
	{level=5,sound="GuitarElectricBassDuet05DannyBoy",length=256,name="ContextMenu_Duet_DannyBoy",actionType="Male",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=1,guitarelectric=0,guitarelectricbass=0,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=1,vocalf=0},
	{level=5,sound="GuitarElectricBassDuet05HouseoftheRisingSun",length=260,name="ContextMenu_Duet_HouseoftheRisingSun",actionType="Male",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=1,guitarelectric=0,guitarelectricbass=0,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=1,vocalf=0},
	{level=6,sound="GuitarElectricBassDuet06Roxanne",length=199,name="ContextMenu_Duet_Roxanne",actionType="Male",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=0,guitarelectric=1,guitarelectricbass=0,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=1,vocalf=0},
	{level=7,sound="GuitarElectricBassDuet07DownUnder",length=195,name="ContextMenu_Duet_DownUnder",actionType="Male",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=0,guitarelectric=1,guitarelectricbass=0,flute=1,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=1,vocalf=0},
	{level=7,sound="GuitarElectricBassDuet07EveryBreathYouTake",length=252,name="ContextMenu_Duet_EveryBreathYouTake",actionType="Male",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=0,guitarelectric=1,guitarelectricbass=0,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=1,vocalf=0},
	{level=7,sound="GuitarElectricBassDuet07LittleBrownJug",length=142,name="ContextMenu_Duet_LittleBrownJug",actionType="Male",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=1,guitarelectric=0,guitarelectricbass=0,flute=0,saxophone=1,trumpet=1,violin=0,drums=0,piano=1,harmonica=0,vocalm=1,vocalf=0},
	{level=9,sound="GuitarElectricBassDuet09Africa",length=291,name="ContextMenu_Duet_Africa",actionType="Male",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=1,guitarelectric=1,guitarelectricbass=0,flute=1,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=1,vocalf=0},
	{level=9,sound="GuitarElectricBassDuet09ImStillStanding",length=181,name="ContextMenu_Duet_ImStillStanding",actionType="Male",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=1,guitarelectric=1,guitarelectricbass=0,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=1,vocalf=0},
	{level=10,sound="GuitarElectricBassDuet10DontYou",length=269,name="ContextMenu_Duet_DontYou",actionType="Male",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=0,guitarelectric=1,guitarelectricbass=0,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=1,vocalf=0},
	{level=10,sound="GuitarElectricBassDuet10HoldtheLine",length=238,name="ContextMenu_Duet_HoldtheLine",actionType="CanDoBackVocal",soundv="GuitarElectricBassDuetVocal10HoldtheLine",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=0,guitarelectric=1,guitarelectricbass=0,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=1,vocalf=0},
}
