require 'Definitions/HairOutfitDefinitions'

local list = {
	["Punk"] = {
		"M_P3Hero",
		"F_P3Hero",
		"F_RickShow",
		"F_SpikedUp",
		"F_SpikedForward",
		"F_SpikedMessy",
		"F_Vi",
		"M_Vi",
		"F_Frank",
		"F_Taurie",
		"M_Taurie",
	},
	["Bandit"] = {
		"F_Oliveira",
		"M_Oliveira",
		"F_Dante",
		"M_Dante",
	},
	["Student"] = {
		"F_Touka",
		"F_ToukaStraight",
		"F_Power",
		"F_PowerTied",
	},
	["ZombiesDontLike"] = {
		"M_P3HeroG1",
		"F_P3HeroG1",
		"M_Redfield",
		"M_Goth",
		"M_Valentine",
		"M_Mitsuru",
		"M_MitsuruPonytail",
		"F_Mitsuru",
		"F_MitsuruPonytail",
		"M_Marie",
		"M_Mikasa",
		"M_MikasaShort",
		"M_MikasaG1",
		"F_Mikasa",
		"F_MikasaG1",
		"F_ErenBun",
		"M_ErenParted",
		"F_Leon",
		"M_Vergil",
		"F_RickShow",
		"F_Vergil",
		"M_Dante",
		"F_Dante",
		"M_KotonePonytail",
		"F_DanteParted",
		"F_Parted",
		"F_PartedMedium",
		"M_Aigis",
		"M_AigisAlt",
		"F_AigisAlt",
		"M_Kotone",
		"M_Rei",
		"M_ReiG1",
		"F_ReiG1",
		"M_Yukari",
		"M_YukariAlt",
		"M_YukariBun",
		"F_Sideswept",
		"M_Curtains",
		"M_Kusanagi",
		"M_Hero",
		"M_HeroTail",
		"M_HeroBun",
		"F_Kusanagi",
		"F_Surfer",
		"F_CurtainsHigh",
		"F_LeonLong",
		"F_PartedSideMedium",
		"F_PartedSide",
		"F_LeonRE4",
		"F_PrincelyShort",
		"F_LeonLong",
		"F_Princely",
		"M_RedfieldLow",
		"F_AshBowl",
		"F_Ash",
		"F_AshShort",
		"F_AshSlick",
		"F_Logan",
		"M_PartedTail",
		"M_Touka",
		"M_ToukaStraight",
		"M_StraightCutBob",
		"M_MessyBob",
		"M_Jeanette",
		"M_RedfieldMessy",
		"M_BobSlick",
		"M_Ashley",
		"M_OvereyeShaggy",
		"M_OvereyeShaggyG1",
		"F_OvereyeShaggy",
		"F_OvereyeShaggyG1",
		"M_OvereyeShaggyLeft",
		"M_OvereyeShaggyLeftG1",
		"F_OvereyeShaggyLeft",
		"F_OvereyeShaggyLeftG1",
		"M_Power",
		"M_PowerTied",
		"M_Zarina",
		"M_ZarinaCurly",
	},
}

local HairOutfitDefinitions_haircutDefinition = HairOutfitDefinitions.haircutDefinition
local table_insert = table.insert
for outfit, hairs in pairs(list) do
	for i, hair in ipairs(hairs) do
		local cat = {name = hair, onlyFor = outfit}
		table_insert(HairOutfitDefinitions_haircutDefinition, cat)
	end
end
list = nil