HitmanNames = HitmanNames or {}

HitmanNames.GenerateName = function(female)
    local firstname
    if female then
        firstname = HitmanUtils.Choice(HitmanNames.Female.FirstNames)
    else
        firstname = HitmanUtils.Choice(HitmanNames.Male.FirstNames)
    end
    local surname = HitmanUtils.Choice(HitmanNames.Surnames)

    return firstname .. " " .. surname
end

HitmanNames.Male = HitmanNames.Male or {}
HitmanNames.Male.FirstNames = HitmanNames.Male.FirstNames or {}

table.insert(HitmanNames.Male.FirstNames, "Liam")
table.insert(HitmanNames.Male.FirstNames, "Noah")
table.insert(HitmanNames.Male.FirstNames, "Oliver")
table.insert(HitmanNames.Male.FirstNames, "Elijah")
table.insert(HitmanNames.Male.FirstNames, "James")
table.insert(HitmanNames.Male.FirstNames, "William")
table.insert(HitmanNames.Male.FirstNames, "Benjamin")
table.insert(HitmanNames.Male.FirstNames, "Lucas")
table.insert(HitmanNames.Male.FirstNames, "Henry")
table.insert(HitmanNames.Male.FirstNames, "Theodore")
table.insert(HitmanNames.Male.FirstNames, "Jack")
table.insert(HitmanNames.Male.FirstNames, "Levi")
table.insert(HitmanNames.Male.FirstNames, "Alexander")
table.insert(HitmanNames.Male.FirstNames, "Jackson")
table.insert(HitmanNames.Male.FirstNames, "Mateo")
table.insert(HitmanNames.Male.FirstNames, "Daniel")
table.insert(HitmanNames.Male.FirstNames, "Michael")
table.insert(HitmanNames.Male.FirstNames, "Mason")
table.insert(HitmanNames.Male.FirstNames, "Sebastian")
table.insert(HitmanNames.Male.FirstNames, "Ethan")
table.insert(HitmanNames.Male.FirstNames, "Logan")
table.insert(HitmanNames.Male.FirstNames, "Owen")
table.insert(HitmanNames.Male.FirstNames, "Samuel")
table.insert(HitmanNames.Male.FirstNames, "Jacob")
table.insert(HitmanNames.Male.FirstNames, "Asher")
table.insert(HitmanNames.Male.FirstNames, "Aiden")
table.insert(HitmanNames.Male.FirstNames, "John")
table.insert(HitmanNames.Male.FirstNames, "Joseph")
table.insert(HitmanNames.Male.FirstNames, "Wyatt")
table.insert(HitmanNames.Male.FirstNames, "David")
table.insert(HitmanNames.Male.FirstNames, "Leo")
table.insert(HitmanNames.Male.FirstNames, "Luke")
table.insert(HitmanNames.Male.FirstNames, "Julian")
table.insert(HitmanNames.Male.FirstNames, "Hudson")
table.insert(HitmanNames.Male.FirstNames, "Grayson")
table.insert(HitmanNames.Male.FirstNames, "Matthew")
table.insert(HitmanNames.Male.FirstNames, "Ezra")
table.insert(HitmanNames.Male.FirstNames, "Gabriel")
table.insert(HitmanNames.Male.FirstNames, "Carter")
table.insert(HitmanNames.Male.FirstNames, "Isaac")
table.insert(HitmanNames.Male.FirstNames, "Jayden")
table.insert(HitmanNames.Male.FirstNames, "Luca")
table.insert(HitmanNames.Male.FirstNames, "Anthony")
table.insert(HitmanNames.Male.FirstNames, "Dylan")
table.insert(HitmanNames.Male.FirstNames, "Lincoln")
table.insert(HitmanNames.Male.FirstNames, "Thomas")
table.insert(HitmanNames.Male.FirstNames, "Maverick")
table.insert(HitmanNames.Male.FirstNames, "Elias")
table.insert(HitmanNames.Male.FirstNames, "Josiah")
table.insert(HitmanNames.Male.FirstNames, "Charles")

HitmanNames.Female = HitmanNames.Female or {}
HitmanNames.Female.FirstNames = HitmanNames.Female.FirstNames or {}
table.insert(HitmanNames.Female.FirstNames, "Olivia")
table.insert(HitmanNames.Female.FirstNames, "Emma")
table.insert(HitmanNames.Female.FirstNames, "Charlotte")
table.insert(HitmanNames.Female.FirstNames, "Amelia")
table.insert(HitmanNames.Female.FirstNames, "Sophia")
table.insert(HitmanNames.Female.FirstNames, "Isabella")
table.insert(HitmanNames.Female.FirstNames, "Ava")
table.insert(HitmanNames.Female.FirstNames, "Mia")
table.insert(HitmanNames.Female.FirstNames, "Evelyn")
table.insert(HitmanNames.Female.FirstNames, "Luna")
table.insert(HitmanNames.Female.FirstNames, "Harper")
table.insert(HitmanNames.Female.FirstNames, "Camila")
table.insert(HitmanNames.Female.FirstNames, "Gianna")
table.insert(HitmanNames.Female.FirstNames, "Aria")
table.insert(HitmanNames.Female.FirstNames, "Ella")
table.insert(HitmanNames.Female.FirstNames, "Scarlett")
table.insert(HitmanNames.Female.FirstNames, "Grace")
table.insert(HitmanNames.Female.FirstNames, "Chloe")
table.insert(HitmanNames.Female.FirstNames, "Victoria")
table.insert(HitmanNames.Female.FirstNames, "Riley")
table.insert(HitmanNames.Female.FirstNames, "Zoey")
table.insert(HitmanNames.Female.FirstNames, "Lily")
table.insert(HitmanNames.Female.FirstNames, "Aurora")
table.insert(HitmanNames.Female.FirstNames, "Hazel")
table.insert(HitmanNames.Female.FirstNames, "Penelope")
table.insert(HitmanNames.Female.FirstNames, "Layla")
table.insert(HitmanNames.Female.FirstNames, "Nora")
table.insert(HitmanNames.Female.FirstNames, "Mila")
table.insert(HitmanNames.Female.FirstNames, "Stella")
table.insert(HitmanNames.Female.FirstNames, "Ellie")
table.insert(HitmanNames.Female.FirstNames, "Abigail")
table.insert(HitmanNames.Female.FirstNames, "Addison")
table.insert(HitmanNames.Female.FirstNames, "Lucy")
table.insert(HitmanNames.Female.FirstNames, "Bella")
table.insert(HitmanNames.Female.FirstNames, "Nova")
table.insert(HitmanNames.Female.FirstNames, "Ivy")
table.insert(HitmanNames.Female.FirstNames, "Emily")
table.insert(HitmanNames.Female.FirstNames, "Madelyn")
table.insert(HitmanNames.Female.FirstNames, "Peyton")
table.insert(HitmanNames.Female.FirstNames, "Savannah")
table.insert(HitmanNames.Female.FirstNames, "Sophie")
table.insert(HitmanNames.Female.FirstNames, "Delilah")
table.insert(HitmanNames.Female.FirstNames, "Skylar")
table.insert(HitmanNames.Female.FirstNames, "Aubrey")
table.insert(HitmanNames.Female.FirstNames, "Aaliyah")
table.insert(HitmanNames.Female.FirstNames, "Brooklyn")
table.insert(HitmanNames.Female.FirstNames, "Claire")
table.insert(HitmanNames.Female.FirstNames, "Daisy")
table.insert(HitmanNames.Female.FirstNames, "Natalie")
table.insert(HitmanNames.Female.FirstNames, "Leah")

HitmanNames = HitmanNames or {}
HitmanNames.Surnames = HitmanNames.Surnames or {}

HitmanNames = HitmanNames or {}
HitmanNames.Surnames = HitmanNames.Surnames or {}

table.insert(HitmanNames.Surnames, "Smith")
table.insert(HitmanNames.Surnames, "Johnson")
table.insert(HitmanNames.Surnames, "Williams")
table.insert(HitmanNames.Surnames, "Brown")
table.insert(HitmanNames.Surnames, "Jones")
table.insert(HitmanNames.Surnames, "Garcia")
table.insert(HitmanNames.Surnames, "Miller")
table.insert(HitmanNames.Surnames, "Davis")
table.insert(HitmanNames.Surnames, "Rodriguez")
table.insert(HitmanNames.Surnames, "Martinez")
table.insert(HitmanNames.Surnames, "Hernandez")
table.insert(HitmanNames.Surnames, "Lopez")
table.insert(HitmanNames.Surnames, "Gonzalez")
table.insert(HitmanNames.Surnames, "Wilson")
table.insert(HitmanNames.Surnames, "Anderson")
table.insert(HitmanNames.Surnames, "Thomas")
table.insert(HitmanNames.Surnames, "Taylor")
table.insert(HitmanNames.Surnames, "Moore")
table.insert(HitmanNames.Surnames, "Jackson")
table.insert(HitmanNames.Surnames, "Martin")
table.insert(HitmanNames.Surnames, "Lee")
table.insert(HitmanNames.Surnames, "Perez")
table.insert(HitmanNames.Surnames, "Thompson")
table.insert(HitmanNames.Surnames, "White")
table.insert(HitmanNames.Surnames, "Harris")
table.insert(HitmanNames.Surnames, "Sanchez")
table.insert(HitmanNames.Surnames, "Clark")
table.insert(HitmanNames.Surnames, "Ramirez")
table.insert(HitmanNames.Surnames, "Lewis")
table.insert(HitmanNames.Surnames, "Robinson")
table.insert(HitmanNames.Surnames, "Walker")
table.insert(HitmanNames.Surnames, "Young")
table.insert(HitmanNames.Surnames, "Allen")
table.insert(HitmanNames.Surnames, "King")
table.insert(HitmanNames.Surnames, "Wright")
table.insert(HitmanNames.Surnames, "Scott")
table.insert(HitmanNames.Surnames, "Torres")
table.insert(HitmanNames.Surnames, "Nguyen")
table.insert(HitmanNames.Surnames, "Hill")
table.insert(HitmanNames.Surnames, "Flores")
table.insert(HitmanNames.Surnames, "Green")
table.insert(HitmanNames.Surnames, "Adams")
table.insert(HitmanNames.Surnames, "Nelson")
table.insert(HitmanNames.Surnames, "Baker")
table.insert(HitmanNames.Surnames, "Hall")
table.insert(HitmanNames.Surnames, "Rivera")
table.insert(HitmanNames.Surnames, "Campbell")
table.insert(HitmanNames.Surnames, "Mitchell")
table.insert(HitmanNames.Surnames, "Carter")
table.insert(HitmanNames.Surnames, "Roberts")
table.insert(HitmanNames.Surnames, "Gomez")
table.insert(HitmanNames.Surnames, "Phillips")
table.insert(HitmanNames.Surnames, "Evans")
table.insert(HitmanNames.Surnames, "Turner")
table.insert(HitmanNames.Surnames, "Diaz")
table.insert(HitmanNames.Surnames, "Parker")
table.insert(HitmanNames.Surnames, "Cruz")
table.insert(HitmanNames.Surnames, "Edwards")
table.insert(HitmanNames.Surnames, "Collins")
table.insert(HitmanNames.Surnames, "Reyes")
table.insert(HitmanNames.Surnames, "Stewart")
table.insert(HitmanNames.Surnames, "Morris")
table.insert(HitmanNames.Surnames, "Morales")
table.insert(HitmanNames.Surnames, "Murphy")
table.insert(HitmanNames.Surnames, "Cook")
table.insert(HitmanNames.Surnames, "Rogers")
table.insert(HitmanNames.Surnames, "Gutierrez")
table.insert(HitmanNames.Surnames, "Ortiz")
table.insert(HitmanNames.Surnames, "Morgan")
table.insert(HitmanNames.Surnames, "Cooper")
table.insert(HitmanNames.Surnames, "Peterson")
table.insert(HitmanNames.Surnames, "Bailey")
table.insert(HitmanNames.Surnames, "Reed")
table.insert(HitmanNames.Surnames, "Kelly")
table.insert(HitmanNames.Surnames, "Howard")
table.insert(HitmanNames.Surnames, "Ramos")
table.insert(HitmanNames.Surnames, "Kim")
table.insert(HitmanNames.Surnames, "Cox")
table.insert(HitmanNames.Surnames, "Ward")
table.insert(HitmanNames.Surnames, "Richardson")
table.insert(HitmanNames.Surnames, "Watson")
table.insert(HitmanNames.Surnames, "Brooks")
table.insert(HitmanNames.Surnames, "Chavez")
table.insert(HitmanNames.Surnames, "Wood")
table.insert(HitmanNames.Surnames, "James")
table.insert(HitmanNames.Surnames, "Bennett")
table.insert(HitmanNames.Surnames, "Gray")
table.insert(HitmanNames.Surnames, "Mendoza")
table.insert(HitmanNames.Surnames, "Ruiz")
table.insert(HitmanNames.Surnames, "Hughes")
table.insert(HitmanNames.Surnames, "Price")
table.insert(HitmanNames.Surnames, "Alvarez")
table.insert(HitmanNames.Surnames, "Castillo")
table.insert(HitmanNames.Surnames, "Sanders")
table.insert(HitmanNames.Surnames, "Patel")


