function Adjust(Name, Property, Value)
Item = ScriptManager.instance:getItem(Name)
Item:DoParam(Property.." = "..Value)
end

Adjust("Base.BookCarpentry1","Icon","book_chocolate_Carpentry1")
Adjust("Base.BookCarpentry2","Icon","book_chocolate_Carpentry2")
Adjust("Base.BookCarpentry3","Icon","book_chocolate_Carpentry3")
Adjust("Base.BookCarpentry4","Icon","book_chocolate_Carpentry4")
Adjust("Base.BookCarpentry5","Icon","book_chocolate_Carpentry5")

Adjust("Base.BookCooking1","Icon","book_chocolate_Cooking1")
Adjust("Base.BookCooking2","Icon","book_chocolate_Cooking2")
Adjust("Base.BookCooking3","Icon","book_chocolate_Cooking3")
Adjust("Base.BookCooking4","Icon","book_chocolate_Cooking4")
Adjust("Base.BookCooking5","Icon","book_chocolate_Cooking5")

Adjust("Base.BookElectrician1","Icon","book_chocolate_Electrician1")
Adjust("Base.BookElectrician2","Icon","book_chocolate_Electrician2")
Adjust("Base.BookElectrician3","Icon","book_chocolate_Electrician3")
Adjust("Base.BookElectrician4","Icon","book_chocolate_Electrician4")
Adjust("Base.BookElectrician5","Icon","book_chocolate_Electrician5")

Adjust("Base.BookFarming1","Icon","book_chocolate_Farming1")
Adjust("Base.BookFarming2","Icon","book_chocolate_Farming2")
Adjust("Base.BookFarming3","Icon","book_chocolate_Farming3")
Adjust("Base.BookFarming4","Icon","book_chocolate_Farming4")
Adjust("Base.BookFarming5","Icon","book_chocolate_Farming5")

Adjust("Base.BookFishing1","Icon","book_chocolate_Fishing1")
Adjust("Base.BookFishing2","Icon","book_chocolate_Fishing2")
Adjust("Base.BookFishing3","Icon","book_chocolate_Fishing3")
Adjust("Base.BookFishing4","Icon","book_chocolate_Fishing4")
Adjust("Base.BookFishing5","Icon","book_chocolate_Fishing5")

Adjust("Base.BookFirstAid1","Icon","book_chocolate_FirstAid1")
Adjust("Base.BookFirstAid2","Icon","book_chocolate_FirstAid2")
Adjust("Base.BookFirstAid3","Icon","book_chocolate_FirstAid3")
Adjust("Base.BookFirstAid4","Icon","book_chocolate_FirstAid4")
Adjust("Base.BookFirstAid5","Icon","book_chocolate_FirstAid5")

Adjust("Base.BookForaging1","Icon","book_chocolate_Foraging1")
Adjust("Base.BookForaging2","Icon","book_chocolate_Foraging2")
Adjust("Base.BookForaging3","Icon","book_chocolate_Foraging3")
Adjust("Base.BookForaging4","Icon","book_chocolate_Foraging4")
Adjust("Base.BookForaging5","Icon","book_chocolate_Foraging5")

Adjust("Base.BookMechanic1","Icon","book_chocolate_Mechanic1")
Adjust("Base.BookMechanic2","Icon","book_chocolate_Mechanic2")
Adjust("Base.BookMechanic3","Icon","book_chocolate_Mechanic3")
Adjust("Base.BookMechanic4","Icon","book_chocolate_Mechanic4")
Adjust("Base.BookMechanic5","Icon","book_chocolate_Mechanic5")

Adjust("Base.BookMetalWelding1","Icon","book_chocolate_MetalWelding1")
Adjust("Base.BookMetalWelding2","Icon","book_chocolate_MetalWelding2")
Adjust("Base.BookMetalWelding3","Icon","book_chocolate_MetalWelding3")
Adjust("Base.BookMetalWelding4","Icon","book_chocolate_MetalWelding4")
Adjust("Base.BookMetalWelding5","Icon","book_chocolate_MetalWelding5")

Adjust("Base.BookBlacksmith1","Icon","book_chocolate_Blacksmith1")
Adjust("Base.BookBlacksmith2","Icon","book_chocolate_Blacksmith2")
Adjust("Base.BookBlacksmith3","Icon","book_chocolate_Blacksmith3")
Adjust("Base.BookBlacksmith4","Icon","book_chocolate_Blacksmith4")
Adjust("Base.BookBlacksmith5","Icon","book_chocolate_Blacksmith5")

Adjust("Base.BookTailoring1","Icon","book_chocolate_Tailoring1")
Adjust("Base.BookTailoring2","Icon","book_chocolate_Tailoring2")
Adjust("Base.BookTailoring3","Icon","book_chocolate_Tailoring3")
Adjust("Base.BookTailoring4","Icon","book_chocolate_Tailoring4")
Adjust("Base.BookTailoring5","Icon","book_chocolate_Tailoring5")

Adjust("Base.BookTrapping1","Icon","book_chocolate_Trapping1")
Adjust("Base.BookTrapping2","Icon","book_chocolate_Trapping2")
Adjust("Base.BookTrapping3","Icon","book_chocolate_Trapping3")
Adjust("Base.BookTrapping4","Icon","book_chocolate_Trapping4")
Adjust("Base.BookTrapping5","Icon","book_chocolate_Trapping5")
