--------------------------------------------------------------------------------------------------
--		----	  |			  |			|		 |				|    --    |      ----			--
--		----	  |			  |			|		 |				|    --	   |      ----			--
--		----	  |		-------	   -----|	 ---------		-----          -      ----	   -------
--		----	  |			---			|		 -----		------        --      ----			--
--		----	  |			---			|		 -----		-------	 	 ---      ----			--
--		----	  |		-------	   ----------	 -----		-------		 ---      ----	   -------
--			|	  |		-------			|		 -----		-------		 ---		  |			--
--			|	  |		-------			|	 	 -----		-------		 ---		  |			--
--------------------------------------------------------------------------------------------------

--Jukebox Tracks

return {
	{genre="pop",sound="Pop1",length=134},
	{genre="pop",sound="Pop2",length=202},
	{genre="pop",sound="Pop3",length=200},
	{genre="pop",sound="Pop4",length=264},
	{genre="pop",sound="Pop5",length=243},
	{genre="pop",sound="Pop6",length=207},
	{genre="pop",sound="Pop7",length=218},
	{genre="pop",sound="Pop8",length=233},
	{genre="pop",sound="Pop9",length=228},
	{genre="pop",sound="Pop10",length=220},
	{genre="pop",sound="Pop11",length=178},
	{genre="pop",sound="Pop12",length=265},
	{genre="pop",sound="Pop13",length=165},
	{genre="pop",sound="Pop14",length=158},
	{genre="pop",sound="Pop15",length=173},
	{genre="pop",sound="Pop16",length=258},
	{genre="pop",sound="Pop17",length=255},
	{genre="pop",sound="Pop18",length=195},
	{genre="pop",sound="Pop19",length=176},
	{genre="pop",sound="Pop20",length=184},
	{genre="pop",sound="Pop21",length=204},
	{genre="pop",sound="Pop22",length=220},
	{genre="pop",sound="Pop23",length=234},
	{genre="pop",sound="Pop24",length=187},
	{genre="pop",sound="Pop25",length=212},
	{genre="pop",sound="Pop26",length=212},
	{genre="pop",sound="Pop27",length=228},
	{genre="pop",sound="Pop28",length=190},
	{genre="pop",sound="Pop29",length=197},
	{genre="pop",sound="Pop30",length=192},
	{genre="pop",sound="Pop31",length=196},
	{genre="pop",sound="Pop32",length=193},
	{genre="pop",sound="Pop33",length=196},
	{genre="pop",sound="Pop34",length=187},
	{genre="pop",sound="Pop35",length=216},
	{genre="pop",sound="Pop36",length=227},
	{genre="pop",sound="Pop37",length=191},
	{genre="pop",sound="Pop38",length=317},
	{genre="pop",sound="Pop39",length=195},
	{genre="pop",sound="Pop40",length=187},
	{genre="pop",sound="Pop41",length=192},
	{genre="pop",sound="Pop42",length=217},
	{genre="pop",sound="Pop43",length=239},
	{genre="pop",sound="Pop44",length=200},
	{genre="pop",sound="Pop45",length=203},
	{genre="pop",sound="Pop46",length=197},
	{genre="pop",sound="Pop47",length=137},
	{genre="pop",sound="Pop48",length=215},
	{genre="pop",sound="Pop49",length=220},
	{genre="pop",sound="Pop50",length=155},
	{genre="pop",sound="Pop51",length=238},
	{genre="pop",sound="Pop52",length=195},
	{genre="pop",sound="Pop53",length=208},
	{genre="pop",sound="Pop54",length=218},
	{genre="pop",sound="Pop55",length=197},
	{genre="pop",sound="Pop56",length=232},
	{genre="pop",sound="Pop57",length=188},
	{genre="pop",sound="Pop58",length=222},
	{genre="pop",sound="Pop59",length=214},
	{genre="pop",sound="Pop60",length=210},
	{genre="pop",sound="Pop61",length=164},
	{genre="pop",sound="Pop62",length=225},
	{genre="pop",sound="Pop63",length=208},
	{genre="pop",sound="Pop64",length=214},
	{genre="pop",sound="Pop65",length=259},
	{genre="pop",sound="Pop66",length=257},
	{genre="pop",sound="Pop67",length=184},
	{genre="pop",sound="Pop68",length=213},
	{genre="pop",sound="Pop69",length=200},
	{genre="pop",sound="Pop70",length=235},
	{genre="pop",sound="Pop71",length=208},
	{genre="pop",sound="Pop72",length=198},
	{genre="pop",sound="Pop73",length=273},
	{genre="pop",sound="Pop74",length=312},
}
