--------------------------------------------------------------------------------------------------
--		----	  |			  |			|		 |				|    --    |      ----			--
--		----	  |			  |			|		 |				|    --	   |      ----			--
--		----	  |		-------	   -----|	 ---------		-----          -      ----	   -------
--		----	  |			---			|		 -----		------        --      ----			--
--		----	  |			---			|		 -----		-------	 	 ---      ----			--
--		----	  |		-------	   ----------	 -----		-------		 ---      ----	   -------
--			|	  |		-------			|		 -----		-------		 ---		  |			--
--			|	  |		-------			|	 	 -----		-------		 ---		  |			--
--------------------------------------------------------------------------------------------------

-- VOCAL DUET TRACKS
return {
	{level=4,sound="VocalDuet04LetsGroove",length=343,name="ContextMenu_04_01_VCD",actionType="Male",isaddon=0,
	banjo=0,trumpet=0,guitaracoustic=0,guitarelectric=1,guitarelectricbass=1,keytar=1,flute=0,saxophone=1,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=0},
	{level=4,sound="VocalDuet04Summertime",length=173,name="ContextMenu_04_02_VCD",actionType="Female",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=1,guitarelectric=0,guitarelectricbass=1,flute=1,saxophone=0,trumpet=1,violin=0,drums=0,piano=1,harmonica=0,vocalm=0,vocalf=0},
	{level=4,sound="VocalDuet04OhSusanna",length=74,name="ContextMenu_04_03_VCD",actionType="Male",isaddon=0,
	banjo=1,keytar=1,guitaracoustic=0,guitarelectric=0,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=0},
	{level=4,sound="VocalDuet04LaBamba",length=139,name="ContextMenu_04_04_VCD",actionType="Male",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=1,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=0},
	{level=4,sound="VocalDuet04OnceInRoyalDavidsCity",length=146,name="ContextMenu_04_05_VCD",actionType="Male",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=0,guitarelectric=0,guitarelectricbass=1,flute=1,saxophone=0,trumpet=1,violin=1,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=0},
	{level=5,sound="VocalDuet05WhenTheSaintsGoMarchingIn",length=104,name="ContextMenu_05_01_VCD",actionType="Male",isaddon=0,
	banjo=1,keytar=1,guitaracoustic=0,guitarelectric=0,guitarelectricbass=0,flute=1,saxophone=1,trumpet=1,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=0},       
	{level=5,sound="VocalDuet05FeeFye",length=149,name="ContextMenu_05_02_VCD",actionType="Male",isaddon=0,
	banjo=1,keytar=1,guitaracoustic=1,guitarelectric=0,guitarelectricbass=1,flute=1,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=0},
	{level=5,sound="VocalDuet05IWannaDanceWithSomebody",length=296,name="ContextMenu_05_03_VCD",actionType="Female",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=0,guitarelectric=1,guitarelectricbass=0,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=0},
	{level=6,sound="VocalDuet06Banjo",length=255,name="ContextMenu_06_01_VCD",actionType="Male",isaddon=0,
	banjo=1,keytar=1,guitaracoustic=1,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=0,vocalf=0}, 
	{level=6,sound="VocalDuet06MyWay",length=275,name="ContextMenu_06_02_VCD",actionType="Male",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=1,guitarelectric=0,guitarelectricbass=1,flute=1,saxophone=1,trumpet=1,violin=1,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=0},  
	{level=6,sound="VocalDuet06SummerOf69",length=204,name="ContextMenu_06_03_VCD",actionType="Male",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=0,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=0}, 
	{level=7,sound="VocalDuet07Creep",length=239,name="ContextMenu_07_01_VCD",actionType="Male",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=0,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=0,vocalf=0},
	{level=7,sound="VocalDuet07Zombie",length=306,name="ContextMenu_07_02_VCD",actionType="Female",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=0,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=0},
	{level=8,sound="VocalDuet08RideLikeTheWind",length=271,name="ContextMenu_08_01_VCD",actionType="Male",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=1,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=1,trumpet=1,violin=1,drums=0,piano=1,harmonica=0,vocalm=0,vocalf=0},
	{level=9,sound="VocalDuet09Radio80",length=189,name="ContextMenu_09_01_VCD",actionType="Male",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=0,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=1,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=0},
	{level=4,sound="VocalFDuet04Greensleeves",length=178,name="ContextMenu_Duet_Greensleeves",actionType="Female",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=1,guitarelectric=0,guitarelectricbass=1,flute=1,saxophone=1,trumpet=0,violin=1,drums=0,piano=1,harmonica=0,vocalm=0,vocalf=0},
	{level=6,sound="VocalFDuet06RiversofBabylon",length=245,name="ContextMenu_Duet_RiversofBabylon",actionType="Female",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=1,guitarelectric=0,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=0},
	{level=7,sound="VocalFDuet07TotalEclipseoftheHeart",length=276,name="ContextMenu_Duet_TotalEclipseoftheHeart",actionType="Female",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=0,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=0,vocalf=0},
	{level=8,sound="VocalFDuet08Rasputin",length=267,name="ContextMenu_Duet_Rasputin",actionType="Female",isaddon=0,
	banjo=1,keytar=1,guitaracoustic=1,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=1,vocalf=0},
	{level=8,sound="VocalFDuet08WhataFeeling",length=234,name="ContextMenu_Duet_WhataFeeling",actionType="Female",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=0,guitarelectric=1,guitarelectricbass=0,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=0},
	{level=9,sound="VocalFDuet09SweetDreams",length=221,name="ContextMenu_Duet_SweetDreams",actionType="Female",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=0,guitarelectric=0,guitarelectricbass=0,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=0,vocalf=0},
	{level=10,sound="VocalFDuet10HoldingOutForAHero",length=351,name="ContextMenu_Duet_HoldingOutForAHero",actionType="Female",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=0,guitarelectric=1,guitarelectricbass=0,flute=0,saxophone=0,trumpet=1,violin=0,drums=0,piano=1,harmonica=0,vocalm=0,vocalf=0},
	{level=5,sound="VocalMDuet05DannyBoy",length=256,name="ContextMenu_Duet_DannyBoy",actionType="Male",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=1,guitarelectric=0,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=0,vocalf=0},
	{level=5,sound="VocalMDuet05HouseoftheRisingSun",length=260,name="ContextMenu_Duet_HouseoftheRisingSun",actionType="Male",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=1,guitarelectric=0,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=0},
	{level=5,sound="VocalMDuet05Maniac",length=265,name="ContextMenu_Duet_Maniac",actionType="Male",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=0,guitarelectric=1,guitarelectricbass=0,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=0},
	{level=5,sound="VocalMDuet05YouSpinMeRound",length=205,name="ContextMenu_Duet_YouSpinMeRound",actionType="Male",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=0,guitarelectric=0,guitarelectricbass=0,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=0},
	{level=6,sound="VocalMDuet06Roxanne",length=199,name="ContextMenu_Duet_Roxanne",actionType="Male",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=0,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=0},
	{level=7,sound="VocalMDuet07DownUnder",length=195,name="ContextMenu_Duet_DownUnder",actionType="Male",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=0,guitarelectric=1,guitarelectricbass=1,flute=1,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=0},
	{level=7,sound="VocalMDuet07EveryBreathYouTake",length=252,name="ContextMenu_Duet_EveryBreathYouTake",actionType="Male",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=0,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=0,vocalf=0},
	{level=7,sound="VocalMDuet07LittleBrownJug",length=142,name="ContextMenu_Duet_LittleBrownJug",actionType="Male",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=1,guitarelectric=0,guitarelectricbass=1,flute=0,saxophone=1,trumpet=1,violin=0,drums=0,piano=1,harmonica=0,vocalm=0,vocalf=0},
	{level=7,sound="VocalMDuet07Kyrie",length=275,name="ContextMenu_Duet_Kyrie",actionType="Male",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=0,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=0},
	{level=8,sound="VocalMDuet08CarryMeBacktoOldVirginny",length=159,name="ContextMenu_Duet_CarryMeBacktoOldVirginny",actionType="Male",isaddon=0,
	banjo=0,keytar=0,guitaracoustic=1,guitarelectric=0,guitarelectricbass=0,flute=1,saxophone=0,trumpet=1,violin=1,drums=0,piano=1,harmonica=0,vocalm=0,vocalf=0},
	{level=8,sound="VocalMDuet08Rasputin",length=267,name="ContextMenu_Duet_Rasputin",actionType="Male",isaddon=0,
	banjo=1,keytar=1,guitaracoustic=1,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=1,drums=0,piano=0,harmonica=0,vocalm=0,vocalf=1},
	{level=9,sound="VocalMDuet09Africa",length=291,name="ContextMenu_Duet_Africa",actionType="Male",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=1,guitarelectric=1,guitarelectricbass=1,flute=1,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=0,vocalf=0},
	{level=9,sound="VocalMDuet09ImStillStanding",length=181,name="ContextMenu_Duet_ImStillStanding",actionType="Male",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=1,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=0,vocalf=0},
	{level=10,sound="VocalMDuet10DontYou",length=269,name="ContextMenu_Duet_DontYou",actionType="Male",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=0,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=0,vocalf=0},
	{level=10,sound="VocalMDuet10HoldtheLine",length=238,name="ContextMenu_Duet_HoldtheLine",actionType="Male",isaddon=0,
	banjo=0,keytar=1,guitaracoustic=0,guitarelectric=1,guitarelectricbass=1,flute=0,saxophone=0,trumpet=0,violin=0,drums=0,piano=1,harmonica=0,vocalm=0,vocalf=0},
}
